version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: exercise-db
    environment:
      MYSQL_ROOT_PASSWORD: apipassword
      MYSQL_DATABASE: apiDB
      MYSQL_USER: api_user
      MYSQL_PASSWORD: apiuserpassword
    ports:
      - "3306:3306"
    networks:
      - pfcti-network
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: technical
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://exercise-db:3306/apiDB
      SPRING_DATASOURCE_USERNAME: api_user
      SPRING_DATASOURCE_PASSWORD: apiuserpassword
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - pfcti-network

networks:
  pfcti-network:
    driver: bridge

volumes:
  mysql-data:
