spring:
  application:
    name: api-rest

  datasource:
    url:  jdbc:h2:file:./data/apidb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelogs-master.json
logging:
  level:
    liquibase: DEBUG