spring:
  application:
    name: TechnicalTest

  datasource:
    url: jdbc:mysql://localhost:3306/test
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelogs-master.json
logging:
  level:
    liquibase: DEBUG

spring-doc:
  swagger-ui:
    path: /swagger

server:
  port: 5000